networks:
  red-clinicamv:
    external: true

volumes:
  db_data: {}
  laravel_storage: {}

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: clinica
      MYSQL_USER: clinica
      MYSQL_PASSWORD: clinica
      MYSQL_ROOT_PASSWORD: root
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks: [red-clinicamv] 

  php:
    image: ghcr.io/sebasrodmag/clinicamv-backend:php-main
    env_file: [ ./secrets/clinica.env ]
    environment:
      MIGRATE_ON_START: "false" # Cambiar a "true" para que se ejecuten los seeders al iniciar el deploy
      SEED_ON_START: "false" # Igual que arriba
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - laravel_storage:/var/www/storage
    healthcheck:
      test: ["CMD-SHELL", "php -r 'exit((int)!@fsockopen(\"127.0.0.1\",9000));'"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 60s #Cuando ejecutemos migraciones, subir el tiempo a 360s para darle tiempo a que se ejecuten. Sino, en 60 esta bien.
    networks: [red-clinicamv]

  api:
    image: ghcr.io/sebasrodmag/clinicamv-backend:api-main
    restart: unless-stopped
    depends_on:
      php:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/_health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s
    labels:
      # Configuraci√≥n de Traefik para el servicio API
      - traefik.enable=true
      - traefik.docker.network=red-clinicamv

      # --- API principal ---
      - traefik.http.routers.clinicamv-api.rule=Host(`api.clinicamv.lol`)
      - traefik.http.routers.clinicamv-api.entrypoints=websecure
      - traefik.http.routers.clinicamv-api.tls.certresolver=lets
      - traefik.http.routers.clinicamv-api.priority=100
      - traefik.http.routers.clinicamv-api.middlewares=secure-headers@docker

      - traefik.http.routers.clinicamv-api.service=clinicamv-api-svc
      - traefik.http.services.clinicamv-api-svc.loadbalancer.server.port=80

      # --- Docs Swagger (docs.clinicamv.lol) usando el mismo servicio ---
      - traefik.http.routers.clinicamv-docs.rule=Host(`docs.clinicamv.lol`)
      - traefik.http.routers.clinicamv-docs.entrypoints=websecure
      - traefik.http.routers.clinicamv-docs.tls.certresolver=lets
      - traefik.http.routers.clinicamv-docs.service=clinicamv-api-svc
    networks: [red-clinicamv]

  frontend:
    image: ghcr.io/sebasrodmag/clinicamv-frontend:main
    restart: unless-stopped
    labels:
      - traefik.enable=true

      # Router principal de la app
      - traefik.http.routers.front.rule=Host(`app.clinicamv.lol`)
      - traefik.http.routers.front.entrypoints=websecure
      - traefik.http.routers.front.tls.certresolver=lets
      - traefik.http.services.front.loadbalancer.server.port=80
      - traefik.http.routers.front.middlewares=secure-headers@docker

      # Root con WWW para redirigir a app
      - traefik.http.routers.root.rule=Host(`clinicamv.lol`) || Host(`www.clinicamv.lol`)
      - traefik.http.routers.root.entrypoints=websecure
      - traefik.http.routers.root.tls.certresolver=lets
      - traefik.http.routers.root.middlewares=to-app@docker,secure-headers@docker
      - traefik.http.routers.root.service=noop@internal
      - traefik.http.middlewares.to-app.redirectregex.regex=^https?://(www\.)?clinicamv\.lol(/.*)?$
      - traefik.http.middlewares.to-app.redirectregex.replacement=https://app.clinicamv.lol$2
      - traefik.http.middlewares.to-app.redirectregex.permanent=true
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1/_health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks: [red-clinicamv]
  clinicamv-queue:
    image: ghcr.io/sebasrodmag/clinicamv-backend:php-main
    depends_on:
      php:
        condition: service_healthy
      db:
        condition: service_healthy
    # Usa el mismo entorno que php
    env_file: [ ./secrets/clinica.env ]
    entrypoint: [] 
    command: ["php","/var/www/artisan","queue:work","--queue=default,mail,notifications","--sleep=1","--tries=3","--timeout=120","-vvv"]
    working_dir: /var/www
    restart: unless-stopped
    networks: [red-clinicamv]
    volumes:
      - laravel_storage:/var/www/storage
